### ISSUE TITLE
Migrate locality lookup from Mapzen to the Fortis Feature Service

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#13]

**Comment by c-w** [comment]
This is implemented in Fortis-Spark via the [FeatureServiceClient](https://github.com/CatalystCode/project-fortis-spark/blob/769b4594de8f8f43289ac9a83ee9efd132d4a360/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/locations/client/FeatureServiceClient.scala#L10).
