### ISSUE TITLE
Cognitive Services Text Analytics Integration

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#18]
For messages where the language is supported by cognitive services text analytics should have the sentiment score computed by the text analytics service.

**Comment by c-w** [comment]
Integrated with language detection API in [7a43661](https://github.com/CatalystCode/project-fortis-spark/commit/7a43661b7df8880cd891b9b76c58b43efcfc9098).

**Comment by c-w** [comment]
Integrated with sentiment detection API in [3a08ba7](https://github.com/CatalystCode/project-fortis-spark/commit/3a08ba7da914bb51967b2cc800565da3c8d2bbc2).

Example detected sentiments from Facebook posts:

- **0.0 very negative** Hospitals across England reported the cyber attack was causing huge problems to their services and the public in areas affected were being advised to only seek medical care for
 emergencies.
- **0.5 Neutral** Would you stay here?
- **0.5 Neutral** Lance Armstrong told him, "F**k you." Meet the man who stood up against doping in cycling.
- **0.2 slightly negative** "Soldiers are at the entrances to the city. We won't close it off for the moment ... Other soldiers are also deployed inside the city."

**Comment by c-w** [comment]
The Cognitive Services sentiment analysis is available for English, Spanish, French and Portuguese. If we want support for more languages, we could integrate with the polarity module of the OpeNER project which claims support for Dutch, German, French and Italian ([source](https://github.com/opener-project/polarity-tagger#introduction)).

**Comment by c-w** [comment]
The part of OpeNER that provides sentiment analysis is [VU-sentiment-lexicon](https://github.com/opener-project/VU-sentiment-lexicon) which is a Python library. However, the functionality is trivially replicable in other languages:

1. Parse the XML lexicon that maps lemmas to their polarity.
2. For each token in the text to analyze: look up the token's sentiment.
3. Aggregate the sentiments.

**Comment by c-w** [comment]
VU-sentiment-lexicon doesn't include a license. I reached out to the project's maintainer.

**Comment by c-w** [comment]
Sentiment lexicon for Arabic: [fortis-aggregation-spark/models/SWN3_ar_ur.json](https://raw.githubusercontent.com/CatalystCode/project-fortis/master/fortis-aggregation-spark/models/SWN3_ar_ur.json).

**Comment by c-w** [comment]
Mining multi-language sentiment from Tweets [paper](http://www.dai-labor.de/fileadmin/files/publications/narr-twittersentiment-KDML-LWA-2012.pdf).

**Comment by c-w** [comment]
[Word polarity lists for many languages](https://sites.google.com/site/datascienceslab/projects/multilingualsentiment).

**Comment by c-w** [comment]
We got the go-ahead to use the word polarity lists as long as we make sure that the files are called out as GPL.

**Comment by c-w** [comment]
Here is the paper behind the word polarity lists: [Building Sentiment Lexicons for All Major Languages](http://www.aclweb.org/anthology/P14-2063).

**Comment by c-w** [comment]
Models are now on blob, e.g. [fr.zip](https://fortismodels.blob.core.windows.net/sentiment/fr.zip). Each file contains a list of positive words (`pos.txt`) and negative words (`neg.txt`), one per line.

**Comment by c-w** [comment]
Reopening as this was falsely closed. [PR#8](https://github.com/CatalystCode/project-fortis/issues/45) should have closed [Issue#45](https://github.com/CatalystCode/project-fortis/issues/45).

**Comment by c-w** [comment]
PR to finalize implementation of this feature: [PR#9](https://github.com/CatalystCode/project-fortis-spark/pull/9)
