### ISSUE TITLE
Differentiate Objective and Subjective Location Analytics

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#20]
Currently fortis event location is inferred through user shared location, mentions of a location place within the message or through the geotwit approach that evaluates the twitter profile users previously shared location. Fortis should represent topical and emotion based features spatially from a subjective and/or objective context,

**Comment by c-w** [comment]
We have this distinction in the current data model. The objection location is the [AnalyzedItem.sharedLocations field](https://github.com/CatalystCode/project-fortis-spark/blob/e212910dcbb5565c02306148f51c15fc0e893cd0/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/AnalyzedItem.scala#L27) and the subjective location is the [AnalyzedItem.Analysis.locations field](https://github.com/CatalystCode/project-fortis-spark/blob/e212910dcbb5565c02306148f51c15fc0e893cd0/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/AnalyzedItem.scala#L5).

**Comment by c-w** [comment]
Resolving this since it's already implemented.
