### ISSUE TITLE
Add Snapchat Service Integration 

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#23]

**Comment by c-w** [comment]
Snapchat doesn't have an official developer API. I did find a [reverse-engineered API specification](http://gibsonsec.org/snapchat/fulldisclosure/). However, even that doesn't give us a firehose of all content: we're limited to getting the stories of the logged-in user and the stories of the immediate friends of that user. So unless the people using Fortis are very popular on Snapchat, the datasource won't be useful to us.

**Comment by c-w** [comment]
Had a chat with Erik about this a while ago -- pretty sure we shouldn't go down this road for the reasons mentioned above.
