### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#34]
We should research and identify a continuous integration solution for our spark jobs. This could be CircleCI, Travis, etc. Measure of success is running all unit tests when any git push occurs.

**Comment by c-w** [comment]
We currently have a basic CI setup on [Travis](https://travis-ci.org/CatalystCode/project-fortis-spark). As of now, it just runs the [tests](https://github.com/CatalystCode/project-fortis-spark/blob/769b4594de8f8f43289ac9a83ee9efd132d4a360/.travis.yml#L8), but we could also configure it to automatically [publish new versions](https://coderwall.com/p/9b_lfq/deploying-maven-artifacts-from-travis) or do anything else that we can shell-script. We can deploy credentials to Travis by adding them to our config file and encrypting them with the [Travis key](https://docs.travis-ci.com/user/encryption-keys/).

**Comment by c-w** [comment]
Going to close this one off since the success criteria in the original item was fulfilled.
