### ISSUE TITLE
Implement Fortis Connector Subscription Setup

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#35]
Kevin came up with this great idea... Including the proposal below. Basically, we need to support the ability to easily configure which connectors(event hub, instagram, twitter) are enabled for a fortis depoloyment, and the feature extraction strategies(tadaweb, bing, drones, twitter, etc).

[Fortis Registry Proposal](https://github.com/CatalystCode/project-fortis/files/971754/fortis-sparkitecture.txt)

**Comment by kevinhartman** [comment]
# Stream Registration
<img width="1006" alt="screen shot 2017-05-02 at 5 14 11 pm" src="https://cloud.githubusercontent.com/assets/1374024/25641045/203c8e7e-2f60-11e7-9d11-3367aa93595a.png">

The UML diagram above captures the design of the Stream Registration module, which provides a framework for attaching streams to named pipelines, which can later be retrieved as DStream[T]s, where T is the type of the pipeline. Multiple streams can be attached to any one named pipeline regardless of the connector that provides it.

### StreamRegistry
Functions as the repository of streams and their configurations. During initialization, all stream factories will be registered. The subscription client can then attach desired streams to the registry by providing a configuration bundle (dictionary) and the name of the pipeline to which the stream should attach. The Fortis Ingestion Module (#42) will call into the registry to retrieve the corresponding DStream for each of its platform pipelines (FB, Tada, etc.).

### IStreamFactory[T]
The interface for a stream factory. A concrete implementation will define the criteria on which a given stream config can be handled, and provide the implementation for that handling. A concrete implementation will have a direct dependency on the connector library used to provide the stream. Stream factory implementations are not coupled to the Stream Registry module/package, so new factory types of any kind can easily be registered from third party libraries.

## Fortis Ingestion's Usage
Fortis's ingestion module will likely have a code-path/pipeline for each kind of social media platform from which it can ingest (Facebook, Twitter, TadaWeb, Instagram, etc.). Each pipeline will retrieve a DStream[T] from the StreamRegistry where T corresponds to the model used to represent its events. In this way, the logic of aggregation from a custom model T into the Fortis analyzed event type is deferred to the specific code-path for the service. 

There will also be a pipeline defined for custom events of type FortisGenericEvent. Instances of KafkaStreamFactory[FortisGenericEvent] and EventHubStreamFactory[FortisGenericEvent] will be registered to handle custom user-defined streams over these services.

**Comment by kevinhartman** [comment]
Implemented by the [stream provider module](/CatalystCode/project-fortis-spark/tree/b25d3ec790ed1606ab10aedef86fa71b6df4e45c/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/streamprovider) and [corresponding factories](/CatalystCode/project-fortis-spark/tree/b25d3ec790ed1606ab10aedef86fa71b6df4e45c/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/streamfactories). Tests available [here](/CatalystCode/project-fortis-spark/tree/b25d3ec790ed1606ab10aedef86fa71b6df4e45c/src/test/scala/com/microsoft/partnercatalyst/fortis/spark/streamprovider).

Additional factory implementations will be captured in separate issues.
