### ISSUE TITLE
Connector Polling Abstractions

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#36]
Clemens already started this and may be near completion stage, but basically the foundational abstraction classes around how the instragram, snapchat and facebook connectors will poll the upstream data source, as streaming services are unavailable. This should also include some unit tests as well.

**Comment by c-w** [comment]
This is implemented by [PollingReceiver.scala](https://github.com/CatalystCode/streaming-instagram/blob/bc4376dfaa9e2066f322c28538e22c2a2f9e9a95/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/streaming/PollingReceiver.scala#L10). It's unfortunately non-trivial to unit-test Spark Streaming, but I'll look more into it.

**Comment by c-w** [comment]
Unit tests added in [a616c37](https://github.com/CatalystCode/streaming-instagram/commit/a616c3799d2caf53f41ec44b5ead762903bffdfb)
