### ISSUE TITLE
Local Spark Deployment Fails on if Twitter userIds are not a long type

### ISSUE THREAD

**Issue by Smarker** [CatalystCode/project-fortis#38]
In [TwitterStreamFactory.scala](https://github.com/CatalystCode/project-fortis/blob/7b540a8ad3abf53cb23201d531a414e8c9aaab36/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/TwitterStreamFactory.scala), twitter userIds are converted to `long` type. One implication of this is if you have a userId like `"01234"` this will become `1234` and lose the leading `0`. If this conversion is not possible, the local deployment fails [here](https://github.com/CatalystCode/project-fortis/blob/7b540a8ad3abf53cb23201d531a414e8c9aaab36/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/TwitterStreamFactory.scala#L140). 

![image](https://user-images.githubusercontent.com/7232635/36755288-c2ad63ca-1bd9-11e8-8e74-4b2a9241a516.png)

Rather than failing, we should first try converting this value to a `twitter userId` (say if the user entered twitter userId as a username). One possible solution would be to use the [twitter4j library](https://github.com/CatalystCode/project-fortis/blob/7b540a8ad3abf53cb23201d531a414e8c9aaab36/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sources/streamfactories/TwitterStreamFactory.scala#L14) already imported in this file and follow these [docs](http://twitter4j.org/javadoc/twitter4j/User.html) the twitter user object to get the userId given a username.

Clemens mentioned that looking up the twitter userId is pretty [heavily rate-limited](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup), so this needs to be taken into consideration for this feature.

If we cannot convert the value to a userId, ignore the value/handle it gracefully

**Comment by c-w** [comment]
Should be resolved by https://github.com/CatalystCode/project-fortis/commit/fa99475a430b86964a41f71b60dcbc1a503fbaa4. This also batches requests in groups of 100 so that we shouldn't be hitting the rate limit.
