### ISSUE TITLE
Instagram Connector

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#38]
Complete the Instagram spark streaming connector with unit tests. We still need to gather LCA guidance for how we should submit our app to instagram, as well as submitting the PR to Apache Bahir.

**Comment by c-w** [comment]
This is implemented by [InstagramUtils.scala](https://github.com/CatalystCode/streaming-instagram/blob/bc4376dfaa9e2066f322c28538e22c2a2f9e9a95/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/streaming/instagram/InstagramUtils.scala#L12) which gives us a similar interface to other Spark Streaming connectors like Apache Bahir's [TwitterUtils.scala](https://github.com/apache/bahir/blob/fd4c35fc9f7ebb57464d231cf5d66e7bc4096a1b/streaming-twitter/src/main/scala/org/apache/spark/streaming/twitter/TwitterUtils.scala#L28). There are also some unit tests for the Instagram API integration, but more importantly we may want to have some integration tests that run on a schedule to alert us to any breaking changes in the Instagram API. To implement this, we'd have to figure out an environment for the test to run (e.g. [Travis cron job](https://docs.travis-ci.com/user/cron-jobs/)) and how to securely publish an Instagram token to that environment.

**Comment by c-w** [comment]
I've gotten in touch with the Bahir folks about submitting our connector to their project. Let's see where the conversation goes.

Some references:
- [Bahir repo](https://github.com/apache/bahir)
- [Contributing guide](http://bahir.apache.org/contributing/)
- [No issues pertaining to Instagram in their tracker](https://issues.apache.org/jira/issues/?jql=project%20%3D%20BAHIR%20AND%20text%20~%20%22instagram%22)

**Comment by c-w** [comment]
For publishing access keys to Travis for integration tests: we can encrypt them using their public key and then include them in the .travis.yml ([how-to](https://docs.travis-ci.com/user/encryption-keys/))

**Comment by c-w** [comment]
Made a [request](https://issues.sonatype.org/browse/OSSRH-31003) to sonatype to get a group-id and artifact-id under which we can publish the package to maven.

**Comment by c-w** [comment]
The sonatype release flow worked and our group id (`com.github.catalystcode`) now syncs to Maven central. [Example release](https://search.maven.org/#artifactdetails%7Ccom.github.catalystcode%7Cstreaming-instagram_2.11%7C0.0.1-alpha%7Cjar).
