### ISSUE TITLE
Standup Tims OSM Feature Service (database)

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#39]
We should setup Tims feature service which fetches spatial shapes from OSM. This will involve running the feature collector for all shapes in the world and index into postgres.

**Comment by Smarker** [comment]
@erikschlegel stated:
![image](https://user-images.githubusercontent.com/7232635/27708930-67e933de-5ce8-11e7-93e7-312f7f92d981.png)

**To complete the task you will need to make sure both steps are completed:**
![image](https://user-images.githubusercontent.com/7232635/27708985-8ef85a72-5ce8-11e7-8564-7ccadebd6332.png)

For this task, I believe this command might be useful:
```pg_dump <master_postgres_db> | psql <target_postgres_db>```

**Comment by c-w** [comment]
Proposed plan:

1. Write a script that runs `pg_dump` on Tim's master DB and pushes the dump to Azure blob. This script can be run manually or on a schedule from some VM in Azure.
2. When we deploy a new Fortis site, set up a new Postgres instance.
3. After the instance is set up, download the dump file from blob and use `psql` to fill the database.

**Comment by c-w** [comment]
[Azure documentation for hosted Postgres](https://docs.microsoft.com/en-us/azure/postgresql/quickstart-create-server-database-azure-cli).

**Comment by c-w** [comment]
Pseudo-code for the proposed solution:

```sh
resource_group="..."
location="..."
admin_password="..."

db_admin="fortis-admin"
db_name="fortis-feature-service-db"
db_tier="Basic"
db_compute="50"

az postgres server create \
  --resource-group "${resource_group}" \
  --name "${db_name}" \
  --location "${location}" \
  --admin-user "${db_admin}" \
  --admin-password "${admin_password}" \
  --performance-tier "${db_tier}" \
  --compute-units "${db_compute}" \
  --version 9.6

az postgres server firewall-rule create \
  --resource-group "${resource_group}" \
  --server "${db_name}" \
  --name AllowAllIps \
  --start-ip-address 0.0.0.0 \
  --end-ip-address 255.255.255.255

db_host="$(az postgres server show --resource-group "${resource_group}" --name "${db_name}" | jq ".fullyQualifiedDomainName")"

curl "https://path/to/fortis/blob/storage/db.dump" |
psql \
  --host="${db_host}" \
  --port=5432 \
  --username="${db_admin}@${db_name}" \
  --dbname="postgres"
```

**Comment by c-w** [comment]
@erikschlegel Is working on standing up the featureService that sits in front of the DB via Deis.

**Comment by c-w** [comment]
All scripts verified to work end-to-end with Azure-hosted Postgres so resolving this issue. Ask me if you need a sample connection string.

Note that before the featureService can make use of the Azure-hosted Postgres, [featureService#4](https://github.com/CatalystCode/featureService/pull/4) will have to be merged.
