### ISSUE TITLE
Migrate Fortis Pipeline to Event Hub

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#4]
Currently, all fortis events are ingested into queues, which add significant latency to the pipeline. The initial point of entry should be a single event hub where the supported data contract is an unoppinionated and  flexible schema. The other advantage is one can publish sensor data to the Fortis pipeline.

**Comment by c-w** [comment]
This is no longer necessary given that we're moving all the processing to Spark.
