### ISSUE TITLE
Implement NLP Location Feature Extraction Mod

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#40]
Implement the NLP feature extraction scala modules to infer places from tokenized text. The feature service should be used as the source repository for all places in the world. We'll need to implement the cache / hashing approach for how we'll be able to perform a low latent approach for performing this lookup.

**Comment by c-w** [comment]
Existing location inference Azure Function: [LocationInferenceProcessor](https://github.com/CatalystCode/project-fortis-azure-functions/tree/c136765c02fb68a3c19b93b675a8c877d3f95c5b/LocationInferenceProcessor)

**Comment by c-w** [comment]
Rephrasing the high-level flow of the existing implementation:

```py
def find_location(user_id, sentence, shared_location)
    if shared_location:
        # already got it in memory, convert lat/long to json
        return parse_shared_location(shared_location)
    
    try:
        # get location for user from azure table
        return fetch_locations_from_twitter(user_id)
    except KeyError:
        pass

    # call postgres to get a list of all locations and synonyms
    # then build lookup table of synonym->canonical location
    #
    # now extract the location entities from the sentence using nlp
    # and then map them to the canonical form
    return find_location(sentence)
```

**Comment by c-w** [comment]
New implementation will split out the generic parts ("find locations from service via NLP") from the domain-specific parts ("find location for a Twitter user").

**Comment by c-w** [comment]
High-level pseudo-code for the locations-from-sentence feature, in TypeScript-like syntax:

```ts
export function extractLocations(text: string, bbox: Bbox): Feature[] {
    // get locations in text via named entity extraction
    const locationsInText = extractNamedEntities(text).filter(x => x.type === 'Place').map(x => x.name);

    // get locations in bounding box from feature service
    const locationsInBbox = fetchFeaturesInBbox(bbox).features;

    // intersect the two
    return locationsInBbox.filter(loc => locationsInText.indexOf(loc.name) !== -1);
}

function extractNamedEntities(text: string): Entity[] {
    // call Stanford CoreNLP NER API
}

function fetchFeaturesInBbox(bbox: Bbox): {features: Feature[]} {
    // call https://github.com/timfpark/featureService endpoint
    // GET /bbox/:north/:west/:south/:east
}

interface Bbox {
    north: number;
    west: number;
    south: number;
    east: number;
}

interface Entity {
    type: string;
    name: string;
    confidence: number;
}

interface Feature {
    createAt: number;
    updatedAt: number;
    hull: Geometry;
    name: string;
    id: string;
    layer: string;
    properties: Properties;
}

interface Geometry {
    type: string;
    coordinates: number[][];
}

interface Properties {
    names: { [language: string]: string };
    tags: string[];
    elevation: number;
}
```

**Comment by c-w** [comment]
There are some licensing issues with the named-entity recognizers (Stanford CoreNLP is GPLv3, many of the Apache v2 licensed ones are not as good). Plus, it turns out we may not need the named-entity extraction after all: we already have a list of all the synonyms for a given place, so we should be able to just do naive string-matching.

**Comment by c-w** [comment]
Proposed architecture for the locations feature extractor:

![image](https://cloud.githubusercontent.com/assets/1086421/25628570/908f1b28-2f1b-11e7-8e57-fc9ef416c3ad.png)

**Comment by c-w** [comment]
The basic functionality of location inference by ngram matching is implemented by [LocationsExtractor](https://github.com/CatalystCode/project-fortis-spark/blob/5ffb937db20c5a92923ed67a50a5a2703aa2f075/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/locations/LocationsExtractor.scala#L15) ([usage example](https://github.com/CatalystCode/project-fortis-spark/blob/5ffb937db20c5a92923ed67a50a5a2703aa2f075/src/test/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/locations/LocationsExtractorSpec.scala#L40-L55)).

**Comment by c-w** [comment]
We need to consider mis-spellings and have a fast way to lookup all candidates by edit-distance, e.g. via a [BK-tree](http://blog.notdot.net/2007/4/Damn-Cool-Algorithms-Part-1-BK-Trees).

**Comment by c-w** [comment]
We don't have a public deployment of the [featureService](https://github.com/timfpark/featureService) yet so I'm integrating against a local deployment:

```
git clone git@github.com:timfpark/featureService.git
cd featureService
npm install

export FEATURES_CONNECTION_STRING=postgres://.../features
export APPINSIGHTS_INSTRUMENTATIONKEY=...
export PORT=8080
npm start
```

**Comment by c-w** [comment]
Integrated with the featureService in [11cb842](https://github.com/CatalystCode/project-fortis-spark/commit/11cb842ac58c67ac0d46358e09126d2d6f2fd47b). Updated diagram above with the implementation.

**Comment by c-w** [comment]
Extract of running the current locations extractor (centered around the Vancouver/Seattle area) on the Twitter stream:

```tsv
@PicPublic thank you for the follow! Hope you enjoy the photos. Some(wof-101740987-Hope)

Marlyn Monroe portrait Handmade with rice straw. Have U seen it? Great gift for a Marilyn Monroe fan https://t.co/iMsoXuPhL6 via @Etsy       Some(wof-101729901-Monroe)

RT @wikileaks: Clinton: I take "absolute personal responsibility" for election loss and would have won but for "WikiLeaks" & FBI https://t.à    Some(wof-101730883-Clinton)

RT @VisitFaroe: Built by @BritishArmy during their #FaroeIslands #WW2 occupation, Atlantic Airways is getting ready to departure frà    Some(wof-907128885-Atlantic),Some(wof-85869093-Atlantic)

RT @Conteholic: Thibaut Courtois has hurt his right ankle again but is determined to play through the pain in Chelsea's remaining fà    Some(wof-890536721-Chelsea),Some(wof-85810585-Chelsea)

RT @marissareber09: Happy Birthday Kenzie!!??? hope you had a wonderful day, and fhockey won't be the same without you?? @KenzieUlrich httpà    Some(wof-101740987-Hope)

RT @elcosodelapizza: Cuando era chico solφa despertarme a la ma±ana, prender la tele y ver esto https://t.co/9odkP9oOPF Some(wof-101731205-Chico)
```

These are almost exclusively false-positives: "Chico", "Hope", "Clinton", etc. Looks like we'll need the named-entity recognition after all.

**Comment by c-w** [comment]
We'll need to convert all the external location features (e.g. lat/long from Instagram) to the featureService format. Example request: `GET /features/point/${lat=49.2827}/${lng=-123.12}`

**Comment by c-w** [comment]
To improve the locations accuracy, we'll want the ability to narrow the Tweet stream down to a particular geo-fence. We'll likely have to contribute this to Apache Bahir. I've created an issue in their system to track this: [BAHIR-117](https://issues.apache.org/jira/browse/BAHIR-117)

**Comment by c-w** [comment]
Implemented a fix for [BAHIR-117](https://issues.apache.org/jira/browse/BAHIR-117) in [PR-43](https://github.com/apache/bahir/pull/43)

**Comment by c-w** [comment]
Starting to integrate with the NER provided by the [OpeNER project](http://www.opener-project.eu).

**Comment by c-w** [comment]
The OpeNER project is not built with much configurability in mind... I'll have to make some changes to the three projects that we care about: [ixa-pipe-tok](https://github.com/ixa-ehu/ixa-pipe-tok), [ixa-pipe-pos](https://github.com/ixa-ehu/ixa-pipe-pos) and [ixa-pip-nerc](https://github.com/ixa-ehu/ixa-pipe-nerc) so that we can configure from where the code reads its resources. Right now it assumes that all resources are bundled in the jar which doesn't work for us as the resources are licensed under [LGPL-LR](http://infolingu.univ-mlv.fr/DonneesLinguistiques/Lexiques-Grammaires/lgpllr.html) which means that we're fine to use the resources as long as we don't bundle them with our code.

**Comment by c-w** [comment]
Named-entity-recognition (NER) for place detection is now implemented. See [45ed52e](https://github.com/CatalystCode/project-fortis-spark/commit/45ed52eea3d44cf5a49ee50682a96473f6f26b0a) for details.

**Comment by c-w** [comment]
We got both of our PRs against the OpeNER project merged: [ixa-pipe-tok#9](https://github.com/ixa-ehu/ixa-pipe-tok/pull/9) and [ixa-pipe-pos#5](https://github.com/ixa-ehu/ixa-pipe-pos/pull/5).

**Comment by c-w** [comment]
Fixed a few issues and NER now also works on Spark. The memory consumption of the NER pipeline is non-trivial: about 4G all-in for the six languages for which we have models. It also takes a non-insignificant amount of time to load the models from disk (between 10s and 20s depending on the model size; EN is biggest, DE and IT middling, ES, EU and NL smaller).

**Comment by c-w** [comment]
I made some changes to [ixa-pipe-pos](https://github.com/ixa-ehu/ixa-pipe-pos) and [ixa-pip-nerc](https://github.com/ixa-ehu/ixa-pipe-nerc) to reduce memory usage at the expense of more reading from disk. With this setting enabled, we keep the memory usage at just over 2G.

**Comment by c-w** [comment]
Added some code to fetch the models from blob (e.g. [en](https://fortismodels.blob.core.windows.net/public/opener-en.zip), [it](https://fortismodels.blob.core.windows.net/public/opener-it.zip)) if we don't have them locally yet.

**Comment by c-w** [comment]
Reviewed with @erikschlegel; calling this one done.
