### ISSUE TITLE
Implement NLP Topical Feature extraction

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#41]
Tokenize all the words in a message and infer the configured term / keyword and category from the message. we should follow the approach MSR took with http://www.crisislex.org/crisis-lexicon.html . The terms to filter on will be provided via the admin interface of Fortis. 

This functionality will reside within the feature extraction layer of our scala library.

**Comment by c-w** [comment]
If we need person recognition for this feature, we can re-use the infrastructure that's already in place for place recognition. We can use the same approach as [PlaceRecognizer](https://github.com/CatalystCode/project-fortis-spark/blob/164af1e6bbae0adff0c24228faae9312ffe3af5b/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/locations/nlp/PlaceRecognizer.scala#L37) and filter on [Person and/or Organization entities](https://github.com/c-w/kaflib/blob/0048d639d7daec30008458a150e26cbe579a1e7d/src/main/java/ixa/kaflib/Entity.java#L16-L17).

**Comment by kevinhartman** [comment]
Implemented keyword extraction in https://github.com/CatalystCode/project-fortis-spark/pull/2

**Comment by kevinhartman** [comment]
The remainder of this task is captured in https://github.com/CatalystCode/project-fortis-spark/issues/6
