### ISSUE TITLE
Implement Strategy Abstractions

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#42]
Implement the baseline feature extraction strategy abstraction classes. This is the common interfaces and abstract classes shared across the supported data stream strategies(bing, tada, inst, snap, twitter, etc). The final result of a strategy being processed should be a `DStream<T>` where T is the general data schema that we'll persist to Cassandra and Postgres.

**Comment by c-w** [comment]
Initial rough system/dependency overview:

![image](https://cloud.githubusercontent.com/assets/1086421/25545531/215a18fc-2c14-11e7-9c38-c0654b1ede4a.png)

**Comment by c-w** [comment]
Initial data shapes for the "common data model" box: [AnalyzedItem](https://github.com/CatalystCode/project-fortis-spark/blob/6b6b6c339a42dbc09c1d06a149060fe233499ea9/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/AnalyzedItem.scala#L27-L31) and [Analysis](https://github.com/CatalystCode/project-fortis-spark/blob/6b6b6c339a42dbc09c1d06a149060fe233499ea9/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/transforms/AnalyzedItem.scala#L3-L12).

**Comment by c-w** [comment]
@kevinhartman agrees that we'll go forward with this, start implementing and then refine if necessary.

**Comment by c-w** [comment]
This is implemented.
