### ISSUE TITLE
Implement Tadaweb Strategy

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#43]
Events published from tadaweb will be coming down through the EventHub streaming connector. We need to build the strategy processor to transform tada-based messages and thread the message through all the necessary feature extractors. 

You can refer to the existing tadaweb extractor azure function as a reference https://github.com/CatalystCode/project-fortis-azure-functions/tree/0976af9ee079fb826b04411592bd4bd9175a1864/TadawebExtractor

**Comment by kevinhartman** [comment]
Implemented in https://github.com/CatalystCode/project-fortis-spark/pull/3
