### ISSUE TITLE
Reddit stream integration

### ISSUE THREAD

**Issue by jcjimenez** [CatalystCode/project-fortis#47]
Something like Reddit could serve as a useful meta-source for both user-generated content as well as news outlet story references. So, this issue serves as an feature request to integrate https://www.reddit.com/dev/api

The definition of done is a functioning spark stream that can consume and yield AnalyzedItem records for one or more of the following filtered with pre-configured set of terms:

1. /new posts.
2. /rising posts.
3. Posts within /trending subredits.
4. /search posts based on pre-configured term(s).

**Comment by c-w** [comment]
The Reddit API has some quite strict [limits](https://github.com/reddit/reddit/wiki/API) so we wouldn't be able to poll many subreddits and at the same time keep the content reasonably up to date.

However, there also exists a websockets-based [real-time Reddit API](https://blog.pusher.com/pusher-realtime-reddit-api/) that we could integrate with. Sample simple [websocket receiver](https://github.com/rstml/datastax-spark-streaming-demo/blob/c368a89ae3a914576e6b016fc406c902e0698858/src/main/scala/com/datastax/examples/meetup/websocket/WebSocketReceiver.scala#L12).

**Comment by c-w** [comment]
Looking into this a bit more, I'd estimate no more than 1-1.5 days for this. Adding @erikschlegel to comment on whether we want to take this on.

**Comment by erikschlegel** [comment]
Spoke with @jcjimenez this am about Reddit integration. I love the idea and I think the rate limits are fine. Even if we poll it once a minute, I think that should be fine. 

👍 

Erik

**Comment by c-w** [comment]
@erikschlegel Even better: with the stream API provided by pusher, we won't have to poll :)

**Comment by jcjimenez** [comment]
Instructions to create Reddit credentials:

1. Login and click `Preferences`

<img width="1026" alt="reddit_login_welcome" src="https://user-images.githubusercontent.com/1117904/27742298-c0cc0d10-5d7d-11e7-9856-fc1a21a3695b.png">

2. Click `apps`

<img width="1026" alt="reddit_preferences" src="https://user-images.githubusercontent.com/1117904/27742319-d1f9f3ea-5d7d-11e7-9714-c0c3eb9c34bc.png">

3. Click `Create an app`

<img width="968" alt="reddit_create_an_app" src="https://user-images.githubusercontent.com/1117904/27742327-dc993f2c-5d7d-11e7-9dee-37249c31ff18.png">
