### ISSUE TITLE
GraphQL support for the Settings schema.

### ISSUE THREAD

**Issue by jcjimenez** [CatalystCode/project-fortis#49]
Once the Cassandra connector changes are merged, the GraphQL support for the Settings schema (linked below) may be implemented.

https://github.com/CatalystCode/project-fortis-services/blob/91d167025ca6d17891dd9a939e1f7cb1b8df06cc/src/schemas/SettingsSchema.js

**Comment by c-w** [comment]
For the facebookAnalytics query, we can use the Facebook graph API, get the first item in the returned data array and use that item's created_time field.

Sample query:
```
GET /aljazeera/feed
{
  "data": [
    {
      "created_time": "2017-06-29T16:01:39+0000",
      "message": "\"It's the biggest crime of the century and yet they haven't identified the real organisers or those who ordered it.\" http://aje.io/xm9h",
      "id": "7382473689_10155719945103690"
    },
    {
      "created_time": "2017-06-29T15:30:00+0000",
      "message": "Making shoes for Ivanka Trump.",
      "id": "7382473689_10155719348128690"
    },
    ...
  ]
}
```
