### ISSUE TITLE
GraphQL support for the Edges schema

### ISSUE THREAD

**Issue by jcjimenez** [CatalystCode/project-fortis#50]
Once the Cassandra connector changes are merged, the GraphQL support for the Edges schema (linked below) may be implemented.

https://github.com/CatalystCode/project-fortis-services/blob/91d167025ca6d17891dd9a939e1f7cb1b8df06cc/src/schemas/EdgesSchema.js

**Comment by c-w** [comment]
For the `popularLocations`, `timeSeries` and `topSources` resolvers in the we need aggregations which is not something that Cassandra is very good at. Usually the way to handle rolled-up data in Cassandra is to do some extra work while inserting the data to compute a pre-aggregate. I wonder if we need such an aggregate on top of computedtiles table to make these queries efficient. Thoughts?
