### ISSUE TITLE
GraphQL support for the Fact schema

### ISSUE THREAD

**Issue by jcjimenez** [CatalystCode/project-fortis#51]
Once the Cassandra connector changes are merged, the GraphQL support for the Fact schema (linked below) may be implemented.

https://github.com/CatalystCode/project-fortis-services/blob/91d167025ca6d17891dd9a939e1f7cb1b8df06cc/src/schemas/FactSchema.js

**Comment by c-w** [comment]
A fact is an event that is not twitter or facebook.
