### ISSUE TITLE
The resource operation completed with terminal provisioning state 'Failed'. 

### ISSUE THREAD

**Issue by harryanon** [CatalystCode/project-fortis#52]

**Comment by c-w** [comment]
Thanks for reaching out. Could you please follow the steps at https://github.com/CatalystCode/project-fortis/blob/e9843b080e33c2959b1021cb20247ba51a695a6a/project-fortis-pipeline/docs/development-faq.md#how-do-i-debug-issues-with-the-production-deployment-script and check if that helps resolve your problem?
