### ISSUE TITLE
GraphQL support for the Tiles schema

### ISSUE THREAD

**Issue by jcjimenez** [CatalystCode/project-fortis#52]
Once the Cassandra connector changes are merged, the GraphQL support for the Tiles schema (linked below) may be implemented.

https://github.com/CatalystCode/project-fortis-services/blob/91d167025ca6d17891dd9a939e1f7cb1b8df06cc/src/schemas/TilesSchema.js

**Comment by c-w** [comment]
Similar to the [comment](https://github.com/CatalystCode/project-fortis/issues/50#issuecomment-312924868) on the EdgesSchema, the `fetchEdgesByLocations` and `fetchEdgesByBbox` resolvers require aggregations so may need pre-computation.
