### ISSUE TITLE
Some includes in resolvers-cassandra need an extra `../`

### ISSUE THREAD

**Issue by jcjimenez** [CatalystCode/project-fortis#53]
After the resolvers in `project-fortis-services/resolvers-cassandra` were moved from single *.js files and into packages, some `include` statements like this one in `src/resolvers-cassandra/Settings/queries.js` need an an extra `../` path component:

```
const facebookAnalyticsClient = require('../clients/facebook/FacebookAnalyticsClient');
```

**Comment by c-w** [comment]
Resolving as this was merged.
