### ISSUE TITLE
Twitter Data Feed Improvements

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis#8]
Twitter data feed should be driven off user profiles as opposed to collecting all tweets within a given area. This way the user relevancy ranking can be driven off a set of topics and/or demographics.

**Comment by c-w** [comment]
We can implement this trivially once my PR to the Apache Bahir project gets merged.

**Comment by c-w** [comment]
Bahir PR is now merged. We can support arbitrary queries on Twitter as soon as we upgrade our Bahir version.
